### ISSUE TITLE
I have a data question! thanks

### ISSUE THREAD

**Issue by brucelee19960413** [jpwahle/lrec22-d3-dataset#2]
Why is the amount of work described in the author table different from the actual amount in the works file

**Comment by brucelee19960413** [comment]
![image](https://user-images.githubusercontent.com/94457606/207001928-9ab47aac-4516-4afb-8851-6b7d6cb6b110.png)

**Comment by brucelee19960413** [comment]
![image](https://user-images.githubusercontent.com/94457606/207002203-269a2bc7-2ddc-445a-8a03-757e94b48710.png)

**Comment by brucelee19960413** [comment]
![image](https://user-images.githubusercontent.com/94457606/207002314-53a6b1c4-ef2e-4451-8462-51ee8effbf7c.png)

**Comment by brucelee19960413** [comment]
For example, looking up author 2686522 from the authors table has a total of 26 works, but only 5 is actually found from Works

**Comment by jpwahle** [comment]
Hi, tks for the issue 👋🏻

We will look into that soon.
My intuition tells me that the author has more works that are not within DBLP. So they are outside of computer science.

**Comment by jpwahle** [comment]
I looked at this problem, and it seems the intuition was right. Since we are using SemanticScholar data alongside DBLP from v2.0 on, the total numbers relate to everything in SemanticScholar (possible **outside** of DBLP) while the actual works are only **inside** DBLP. We [created this issue](https://github.com/jpwahle/cs-insights-crawler/issues/115) in the cs-insights-crawler, our latest active project working with D3 data.
